# Generated by Django 3.2 on 2021-05-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210501_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.TextField(default='No data', max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
        ),
    ]
